<?php
$sm = 'b|p|m|f|d|t|n|l|g|k|h|j|q|x|zh|ch|sh|r|z|c|s|y|w';//声母
$domainPinyin='niang|nian|niao|ning|nie|nin|niu|ni|nuan|nun|nuo|nu|nve|nv|chuang|shuang|zhuang|chang|cheng|chong|chuai|chuan|guang|huang|jiang|jiong|kuang|liang|qiang|qiong|shang|sheng|'.
					'shuai|shuan|xiang|xiong|zhang|zheng|zhong|zhuai|zhuan|bang|beng|bian|biao|bing|cang|ceng|chai|chan|chao|chen|chou|chua|chui|'.
					'chun|chuo|cong|cuan|dang|deng|dian|diao|ding|dong|duan|fang|feng|fiao|gang|geng|gong|guai|guan|hang|heng|hong|huai|huan|jian|'.
					'jiao|jing|juan|kang|keng|kong|kuai|kuan|lang|leng|lian|liao|ling|long|luan|mang|meng|mian|miao|ming|nang|neng|'.
					'nong|pang|peng|pian|piao|ping|qian|qiao|qing|quan|rang|reng|rong|ruan|sang|seng|shai|shan|shao|shei|shen|shou|shua|shui|'.
					'shun|shuo|song|suan|tang|teng|tian|tiao|ting|tong|tuan|wang|weng|xian|xiao|xing|xuan|yang|ying|yong|yuan|zang|zeng|zhai|zhan|'.
					'zhao|zhei|zhen|zhou|zhua|zhui|zhun|zhuo|zong|zuan|ang|bai|ban|bao|bei|ben|bie|bin|cai|can|cao|cen|cha|che|chi|chu|cou|cui|cun|'.
					'cuo|dai|dan|dao|dei|den|dia|die|diu|dou|dui|dun|duo|eng|fan|fei|fen|fou|gai|gan|gao|gei|gen|gou|gua|gui|gun|guo|hai|han|hao|'.
					'hei|hen|hou|hua|hui|hun|huo|jia|jie|jin|jiu|jue|jun|kai|kan|kao|ken|kou|kua|kui|kun|kuo|lai|lan|lao|lei|lia|lie|lin|liu|lou|'.
					'lun|luo|lve|mai|man|mao|mei|men|mie|min|miu|mou|nai|nan|nao|nei|nen|nou|pai|pan|pao|pei|pen|pie|pin|'.
					'pou|qia|qie|qin|qiu|que|qun|ran|rao|ren|rou|rua|rui|run|ruo|sai|san|sao|sen|sha|she|shi|shu|sou|sui|sun|suo|tai|tan|tao|tie|'.
					'tou|tui|tun|tuo|wai|wan|wei|wen|xia|xie|xin|xiu|xue|xun|yan|yao|yin|you|yue|yun|zai|zan|zao|zei|zen|zha|zhe|zhi|zhu|zou|zui|'.
					'zun|zuo|ai|an|ao|ba|bi|bo|bu|ca|ce|ci|cu|da|de|di|du|ei|en|er|fa|fo|fu|ga|ge|gu|ha|he|hu|ji|ju|ka|ke|ku|la|le|li|lo|lu|lv|ma|'.
					'me|mi|mo|mu|na|ne|ou|pa|pi|po|pu|qi|qu|re|ri|ru|sa|se|si|su|ta|te|ti|tu|wa|wo|wu|xi|xu|ya|ye|yi|yo|yu|za|ze|zi|zu|a|e|o';
$domainAddress='baojixian|linli|yuanjiang|bachu|fuan|gongliu|dingbian|weining|tongnan|hulin|yuanshi|daqing|donge|mengzi|xinghe|luyi|'.
		'chaoyang|pengan|fengkai|simao|geermu|xiangshui|wafangdian|zhenfeng|yangqu|tuoli|xupu|guangan|huairen|balikun|naidong|abazhou|yizheng|'.
		'jiangkou|zhangjiagang|gangcha|fuyun|dongning|yongjia|anren|jiuzhi|jinchuan|jiangyuan|liquan|aohanqi|shuangliu|yanchuan|xinzhou|guzhen|'.
		'shiqu|maguan|zhuanglang|lingtai|dengzhou|yakeshi|suning|damaoqi|lindian|ganzixian|shicheng|longyou|huairou|libo|wenchuan|yinan|mouding|'.
		'guangshui|donglan|kangbao|tanghe|yingshan|nanzhang|jiaxing|changge|dongguang|sanyuan|huating|xintai|nujiang|biru|wanzai|ritu|zitong|'.
		'jinchang|nanchuan|xintian|kaijiang|leishan|guangxi|lingwu|jiangcheng|leling|zhouning|zaoyang|wulateqianqi|wusheng|qianshan|luding|guanghan'.
		'|jianxian|jiajiang|zijin|wanan|panzhihua|ganxian|shiping|keping|zhazuoteqi|dangtu|nanmulin|jingzhou|tiandong|ruian|qiemo|yijun|pingshan'.
		'|faku|ningyang|jinzhou|puxian|guangning|longlin|jiaxian|shaxian|pingtan|heqing|lianyungang|haifeng|tuoba|anqing|yanjin|linzhou|zhangjiakou'.
		'|baoqing|qingxian|chongli|jiangle|taishun|datong|pujiang|anshan|mingxi|yanbian|pingshun|wengniuteqi|zhaoxian|shifang|lianjiang|ruoqiang|'.
		'anlong|qianan|dengta|xinan|wulan|jiangdu|tongwei|hejing|wucheng|qingshuihe|jintang|leqing|liupanshui|qingyangxian|dongyuan|nantong|dayu|'.
		'tongxin|changan|xilin|xiaojin|tongzhou|zunyixian|chongzuo|yongan|helan|cenxi|linzhixian|cuomei|siping|yingjing|hengxian|laohekou|linkou|'.
		'anhua|wuyang|kalaqinqi|sanmen|changwu|qionghai|daofu|dexing|wulatezhongqi|baisha|nanjiang|ziyang|qishan|taihu|luan|shenmu|taiqian|'.
		'shijiazhuang|yuechi|dingan|xianghuangqi|siziwangqi|dashiqiao|guanxian|zhada|baotou|liuhe|zhangjiajie|xingping|yongfeng|lingshui|zhangqiu|'.
		'malipo|danjiangkou|yingkou|tonghe|binzhou|wutai|meihekou|chongzhou|nanchangxian|chengbu|shennongjialinqu|sanhe|dancheng|haicheng|tekesi|'.
		'liuba|chenggong|laishui|zhenan|mulan|handan|yucheng|tengzhou|shunping|wencheng|youyang|nenjiang|huangmei|yunhe|linjiang|dacheng|kelan|'.
		'shehong|longshanjinghe|yuhuan|wangjiang|nancheng|liaocheng|baiyu|nanhai|nima|xinshao|daying|zhuanghe|shanghang|minle|shilin|qiongzhong|'.
		'suiping|nanchong|gongcheng|wuding|kaifengxian|hualong|changning|wuqi|yongcheng|xiangcheng|wuning|zhongjiang|xinjian|jingmen|zhuozi|'.
		'jianning|pingyao|wengan|anhui|dapu|xinzuoqi|jianou|wanding|gaoling|mingshui|xiaogan|qiannan|jiangan|yuzhou|pingba|sajia|huayuan|lezhi|'.
		'bole|muchuan|menyuan|ningdu|huian|heze|gaizhou|jishui|yangshuo|zhengzhou|yiwu|laibin|mianning|liuyang|heping|baishui|suifenhe|lingui|'.
		'jimunai|huojia|eryuan|linquan|lingyun|yanchang|taishan|cili|leibo|huaiyang|kangle|shishou|luoshan|heshui|yingjiang|fusui|zhashui|fanshi|'.
		'bomi|wenxi|shanshan|lingshi|liaoyang|sheyang|xianxian|danleng|mayang|gejiu|keerqinyouyizhongqi|lincheng|elunchun|huaihua|yongchuan|zhangbei|'.
		'ruyuan|ningxia|gaoping|xiangxi|minquan|sihui|gaoming|zhanang|pingwu|hanchuan|linqu|xinning|maduo|bama|yicheng|anyi|cangwu|jianzha|yulin|'.
		'huocheng|guangze|taojiang|ningan|dongxing|chizhou|zhongwei|lueyang|huizhou|shouguang|chenxi|chengcheng|cixian|huangchuan|wuan|huade|'.
		'jingchuan|mancheng|lianghe|wulanhaote|yingxian|nanling|yadong|yunxian|leshan|tulufan|xingtai|jilong|hechi|qiuxian|anxiang|jinzhai|yugan|'.
		'loudi|yanggu|alashan|gaoxian|taining|fuyuan|fanchang|hailaer|jingtai|baojing|yongxin|taizhou|qianguo|huanglong|danzhai|queshan|sixian|laixi'.
		'|quyang|lasa|yongfu|xiangyang|sunan|shizuishan|siyang|panshan|huanjiang|kaihua|xunke|ziyuan|jiangpu|wuxiang|suixi|meishanxian|awati|lianping'.
		'|changyuan|nehe|hengshan|qingxu|angren|fengdu|huma|zouping|maanshan|haian|derong|wangcheng|lixian|yunan|zhongqing|quanzhou|muling|duchang|'.
		'lingshou|guxian|xiajin|tangyin|luotian|zunyi|wuxian|feixian|shangyou|cangxi|balinyouqi|daye|wenquan|hongze|napo|yishui|rushan|honghe|baoding'.
		'|ledong|jiangyin|tongxu|tahe|bayinguoleng|qilian|dahua|xianggelila|binyang|xiangtan|taoyuan|yinzhou|cangshan|suoxian|huzhu|taihe|changshu|'.
		'puyangxian|jurong|gongbujiangda|zhongyang|butuo|guangyuan|hukou|luanxian|luoyang|huaiyinxian|xiuyan|habahe|qinshui|zhuoni|deyang|anning|'.
		'yuqing|luonan|datongxian|guanyang|weihai|dege|changping|yiyuan|anping|tiane|xixiang|yanting|suihua|wuxi|weinan|tonglu|anfu|jiaonan|pinggu|'.
		'hutubi|zhouqu|lipu|heshan|zhangpu|tuokexun|nangong|qingxin|fuyu|jiutai|suide|yunxiao|qianyang|ruoergai|yongde|yushan|qianxian|xinmin|'.
		'dingxiang|suichuan|taiwan|shenchi|fengshan|yingjisha|luoping|pengshui|renhua|ningcheng|yuci|chaoan|zaoqiang|tianjun|xinchang|liancheng|'.
		'qinyuan|qitai|shitai|jingxian|liping|shannan|liangdang|shuangfeng|pingliang|shuicheng|huludao|jishou|danyang|nileke|haixing|duilongdeqing|'.
		'kangping|xuanen|dangxiong|tacheng|lanshan|hechuan|kangding|qinyang|chahaeryouyizhongqi|jianchuan|wenxian|neimenggu|shaoxing|wuzhong|'.
		'xingtaixian|shouxian|jingyan|gansu|wuyishan|maoxian|shenzha|rongan|ximeng|guixi|danba|huanxian|gaotai|xichou|jiangshan|gengma|yunyang|'.
		'chaya|haikou|fangzheng|tuanfeng|duolun|xinlong|xingtang|gaoqing|atushi|dongwuzhumuqinqi|dongfeng|baiyin|tengchong|suiyang|shanyang|ganluo|'.
		'zhangjiachuan|luhuo|yichun|wushan|cuona|pengxi|weixian|hongan|yimen|beian|qujing|huidong|fengrun|bazhou|dafeng|linyou|chaozhou|huangshi|'.
		'zhenba|fujian|xinxing|dongyang|funing|chiping|jinta|lincang|tancheng|xiyang|huadu|fumin|jingxing|fugou|yongding|yanji|hangjinhouqi|moyu|'.
		'mingshan|cangxian|lankao|qinghai|dongguan|malong|yanhe|sishui|lanxian|chengjiang|jiaxiang|luoyuan|xiji|hainan|diqing|nanyang|zhuozhou|'.
		'donghai|jiexiu|tanghai|yanshou|jinggu|tianshui|jingdong|changzhixian|daming|fuliang|haerbin|zhongxian|zhenxiong|hebukesaier|penglai|wuhan|'.
		'shenze|dongsheng|zhijin|gaoan|shuangpai|nielamu|meigu|wuhua|shunde|songyuan|dongming|yilong|yuzhong|wanrong|meizhou|susong|minfeng|'.
		'huhehaote|mingguang|julu|laizhou|huangzhong|nanhua|baofeng|taixing|beihai|pulan|hejin|jiayu|banma|chifeng|pingnan|ruicheng|runan|xuyong|'.
		'gande|mengcun|linan|pingyu|wujiang|zhangshu|guantao|youxi|sanjiang|nanxian|jining|huachuan|lvchun|daxin|cengong|guyuan|rongjiang|shenzhen|'.
		'yantai|mohe|wuhai|honghu|mabian|saga|xishaqundao|chaohu|feixiang|yanggao|houma|chahaeryouyiqianqi|jiangling|tuoketuo|kaiyuan|longhui|hezuo|'.
		'yushu|jimusaer|shule|gaochun|shexian|yangcheng|yangyuan|guizhou|qinzhou|pianguan|helingeer|anqiu|dantu|zhoukou|dongtou|gaoyao|zhuolu|'.
	    'zhenjiang|chongxin|yangchun|heshun|xishuangbanna|qusong|jiacha|gongxian|songming|zibo|yongping|dayi|kuandian|chengkou|fuyang|fengxin|miyun|'.
	    'weishan|laifeng|daan|fuquan|dezhou|yijinhuoluoqi|wengyuan|youyi|laian|ninggang|qiaojia|changsha|chengxian|huangyuan|zhelimumeng|binhai|'.
	    'dechang|mile|xushui|shache|chongming|xiuwen|nongan|yongqing|feixi|ebian|baodi|akesai|duerbote|dazi|heilongjiang|liujiang|shuangjiang|'.
	    'jiangyong|gaoyi|gongzhuling|longyan|shizhu|xingcheng|debao|linzhang|huaan|yangzhou|kaiping|xunwu|hongyuan|haining|lingqiu|suqian|qingan|'.
	    'luquan|zuoyun|xinhua|shiqian|dari|huaining|lintan|qingfeng|datian|enping|qianwei|guangshan|haimen|changyi|mianchi|botou|qingdao|haiyang|'.
	    'sanshui|qijiang|gujiao|huachi|songxian|zhushan|macheng|songzi|changshun|fushan|jidong|zhidan|jiujiangxian|suixian|luzhou|huinan|xishui|'.
	    'lixin|mengjin|antu|shanxi|jiangmen|bijie|dayao|yihuang|yunlong|handanxian|zaozhuang|weishi|wuchuan|wanyuan|dingzhou|xuanhua|xuanwei|wusu|'.
	    'suijiang|yuexi|xinyi|aketao|changhai|fangxian|zeku|jianyang|minhou|anguo|jiaohe|linshu|delingha|shidian|tongdao|fugong|dazu|yangbi|eshan|'.
	    'jiande|jinggangshan|changjiang|longkou|bayan|xiangshan|zhaoyuan|quanjiao|xianning|zhengning|daguan|luojiang|xingren|fucheng|yibin|guangdong|'.
	    'xiajiang|luocheng|linghai|liyang|tangshan|huayin|anze|huilai|danzhou|binchuan|tongshi|tiefa|xiuwu|luzhai|huguan|xunhua|pingyuan|fangcheng|'.
	    'yongchun|dawa|linxiaxian|kenli|hengyangxian|hebi|renshou|taiyuan|ningguo|yueyang|changzhi|shangcai|guangrao|yuhang|gongga|alashanzuoqi|nayong'.
	    '|yandu|fuxian|fangshan|guoluo|qingyun|pixian|kuitun|daxing|gushi|guide|jinyun|weixin|kaili|daxinganling|jinhua|yima|erlianhaote|bianba|anyue'.
	    '|wenjiang|henanxian|zhaotong|heishan|yuxian|dianjiang|longyao|dingtao|gulang|shangsi|jinan|linxi|xianyou|nanan|ansai|linze|tieli|weifang|'.
	    'guangzhou|zherong|licheng|huainan|liangping|bange|langfang|ningqiang|abagaqi|gongshan|wendeng|qianxinan|lintao|huiyang|wubao|huazhou|lushan|'.
	    'shuangyashan|dazhou|gongyi|huinong|yangzhong|chengmai|yiliang|yongning|linxiang|lianhua|dongzhi|xuyi|xinxiang|hefei|huanggang|chenggu|sanming|'.
	    'nanping|xundian|fujin|shanghe|ganzhou|bitu|yifeng|subei|gaolan|qushui|yajiang|tongyu|yushe|longxian|huanghua|yongshan|zhangping|xihe|hanyuan|'.
	    'maqin|huining|jiashi|jiuzhaigou|tongling|ewenke|pingyi|huangshan|jiahe|liangshan|pengzhou|changde|xian|jiamusi|xiwuzhumuqinqi|hezhang|ningde|'.
	    'zanhuang|tongguan|lanzhou|rikaze|anxin|jiangda|shanyin|changshou|changqing|sangzhi|chengwu|yunxi|jilin|xincheng|wenling|shucheng|lvliang|zizhou'.
	    '|dunhuang|longchang|baihe|daishan|yujiang|hejiang|zhenlai|wanquan|fuding|xide|baqing|ganquan|huzhou|renhuai|huarong|yancheng|daixian|lazi|xinhui'.
	    '|xinganmeng|langzhong|liangcheng|jiexi|qingpu|rongchang|zhuxi|wangkui|sandu|etuokeqianqi|minhe|dulan|chenqi|kuerle|jiashan|yitong|haiyan|guzhang'.
	    '|shaoyangxian|jiulong|tongliao|longde|kaifeng|haixi|gongan|longshan|shizong|hengdong|leiwuqi|huozhou|yaoxian|lianshui|qitaihe|renxian|hegang|'.
	    'maoming|xiaochang|nanning|anxian|hunan|yongnian|yangjiang|changling|tongcheng|ganyu|jinsha|zuogong|shimian|fugu|shaowu|yutian|chayu|zigong|'.
	    'longling|huoqiu|jianshui|jianli|dehui|shantou|xiaxian|litang|raoping|pingxiang|fengxiang|yining|huxian|ningxian|yingcheng|yixing|shanglin|luqu'.
	    '|guangping|caoxian|fuqing|yuanan|dangshan|taigu|yongkang|nanao|leye|congjiang|shangluo|putian|luoding|zhaosu|qianxi|nanbu|wushenqi|jingshan|'.
	    'suizhou|pingyin|xuzhou|huaiyin|baixiang|boertala|jianhe|yizhou|tongren|shangrao|hexian|pingtang|jiangxian|wangcang|linfen|yanling|zuoquan|'.
	    'lianshan|jinghai|zhaluteqi|wenshan|cangyuan|shangraoxian|kangxian|jian|chuzhou|langkazi|yilan|beichuan|linhe|zepu|fanxian|luochuan|mozhugongka'.
	    '|shishi|yongshun|pingli|songyang|lianzhou|kelamayi|xingye|dengfeng|zhumadian|xiangyun|yongjing|tianjin|fengzhen|changfeng|yuncheng|enshi|yizhang'.
	    '|luoning|heyuan|jiangxi|xiangning|santai|linxian|wenan|dejiang|xinmi|fenxi|sihong|xunyi|fengcheng|aheqi|shangyu|hebei|muli|jingjiang|zoucheng|'.
	    'shouning|tuquan|guyang|pingdu|yunfu|jiaokou|fenghua|xiuning|xinfeng|yixian|luolong|bazhong|kalaqin|boxing|zhaozhou|tonggu|chengan|leizhou|'.
	    'lingxian|qinghe|nanle|kaixian|hekou|yongshou|yanqing|xiapu|zhuhai|dingri|fangchenggang|hengnan|fengqiu|xiangyin|ankang|pinghu|zongyang|juye|'.
	    'yili|yichang|tangyuan|ningshan|huaian|wanshan|lechang|xiahe|huoshan|jiangzi|pingchang|neihuang|lingshan|hailin|guidong|pingdingshan|xiongxian|'.
	    'zhaoping|zhanyi|dawu|xiantao|tiantai|jingning|shayang|putianxian|renqiu|fengshun|motuo|tonghai|linchuan|jingbian|zhenglanqi|jinmen|qinggang|'.
	    'guangfeng|hailun|jiangyou|jizhou|huangnan|huixian|shiquan|qingtongxia|changxing|liaoning|jinzhong|xinjin|yuanping|zhenghe|xifeng|fusong|changting'.
	    '|yangdong|dachang|jingde|gonghe|pingbian|yingshang|yuanling|shangdu|ninglang|zhangzhou|wangdu|ninghe|fengtai|dengkou|zichang|taibai|xinping|qixia'.
	    '|ceheng|qingshen|sinan|cuoqin|yidu|cele|shangyi|jiangsu|pingquan|dean|ningnan|hami|pucheng|xiaoxian|ezhou|xingning|changdu|hezhou|wulanchabumeng'.
	    '|daxian|lengshuijiang|aershan|donggang|manzhouli|mulei|lingao|xianyang|yaoan|yingde|wuwei|xingguo|neijiang|leping|luntai|qichun|changle|fukang'.
	    '|dehong|sunwu|sichuan|jiayin|hejian|hunchun|jiedong|huitong|langxian|zhengyang|quxian|suiling|suizhong|zhangxian|shanggao|bohu|shangli|changtu'.
	    '|longchuan|xiangyuan|tumotezuoqi|kunshan|genhe|tonghua|huanren|tuyou|guinan|bobai|rongshui|langxi|dalateqi|jiali|maqu|wenchang|zhungeerqi|wulian|'.
	    'daozhen|linshui|junan|ningyuan|hongjiang|luohe|sangri|nanzhao|qingliu|tunliu|mengcheng|naimanqi|hengyang|longsheng|fushun|chongyang|nanpi|huantai'.
	    '|nanzheng|majiang|anyang|emin|linhai|liaozhong|lishui|jiangyan|lingchuan|tianmen|taipusiqi|ruili|luanchuan|guangling|changchun|xichuan|huaibin|'.
	    'nandan|xietongmen|nankang|quannan|huize|emeishan|zixing|nanxi|wufeng|zhaoqing|zhuzhouxian|fufeng|shangzhi|xihua|baode|hanzhong|zhangye|qingyuan|'.
	    'dandong|foping|yangshan|anduo|qiandongnan|nanfeng|linying|ejinaqi|lingbi|jianhu|yutai|anda|luozha|xingxian|gaobeidian|jiangjin|zhongxiang|suyu|'.
	    'lichuan|longan|hongdong|qiqihaer|xiangtanxian|tianyang|fengqing|anyangxian|bayannaoer|hunyuan|beipiao|xixian|sansui|yangxi|chicheng|luanping|'.
	    'huaxian|heishui|arongqi|tongliang|suining|xiaoshan|youxian|zhenkang|maerkang|pizhou|yudu|songxi|hanjiang|zhengan|jingdezhen|guilin|beining|lean|'.
	    'baoxing|dingjie|jiaozuo|chuxiong|xianghe|rudong|dunhua|boyang|wudalianchi|huaiyuan|wuxuan|luannan|hetian|gannan|panjin|anyuan|sheqi|yanjing|'.
	    'fengyang|yuepuhu|nanjian|lufeng|nanhe|quzhou|xichang|guan|dongping|zhangwu|aba|luodian|gaomi|juxian|yuping|ningling|kashi|qingshui|zizhong|pinglu'.
	    '|jiuquan|jinjiang|xingyi|pinghe|changduxian|qingzhen|puning|shaoxingxian|tunchang|shaoshan|pingding|xichong|lanping|boai|zhengding|xinle|wangmo|'.
	    'weihui|zunhua|shuangcheng|heihe|nierong|qihe|wuyuan|nanchang|songtao|xuchang|zhaodong|qiongshan|baiquan|wuchang|linqing|juancheng|xuchangxian|'.
	    'xincai|jingxi|shanghai|ganzi|qiyang|ledu|dingnan|xingzi|shangqiu|guiping|wuqia|panyu|wushi|hequ|gucheng|nanshaqundao|luxian|duyun|eerguna|jiyang'.
	    '|ningjin|geji|kailu|molidawa|zhijiang|keerqinzuoyizhongqi|heshuo|qiongjie|wenshui|zhenping|wangqing|yanshan|xuwen|gangu|zhaojue|menglian|bangbu|'.
	    'guigang|huili|shenyang|suzhou|shuyang|xiushui|jianchang|yinchuan|qujiang|meishan|luopu|taijiang|jianshi|xianggan|hangzhou|shaoyang|shaya|yongdeng'.
	    '|puge|linwu|yexian|youyu|hulan|dali|tianzhu|changyang|zhejiang|basu|shandan|baokang|baishan|huaning|minqin|midu|feicheng|gaozhou|huolinguole|'.
	    'haibei|zhenning|linyi|guoyang|hubei|haidong|yunmeng|guanling|jianghua|dongkou|raohe|xilinguolemeng|neiqiu|pingan|huaiji|akesu|changdao|shanxian'.
	    '|nanhui|shuozhou|zhuzhou|yangxian|tongxiang|jiaozhou|huimin|jieyang|taonan|dingxing|liling|alashanyouqi|rugao|qixian|zhongshan|gongjue|xinbin|'.
	    'gangba|hengshui|pengyang|shenxian|xinyang|pengshan|miyang|changbai|meixian|xinglong|yian|gaer|ninghua|xiangxiang|shenqiu|wenshang|wuzhi|hanshan|'.
	    'peixian|huishui|yongchang|rucheng|panshi|qingjian|ali|longhua|tongzi|puyang|yuanqu|xinyu|luliang|wuxue|wudi|huaping|linzhi|gulin|mojiang|zhongba'.
	    '|guangchang|zhuji|qianjiang|gaoyang|xinxiangxian|wulumuqi|jinning|keshiketengqi|longzi|minqing|langao|guichi|zhecheng|zaduo|tangxian|fenyang|'.
	    'songpan|keshan|ningming|sunitezuoqi|shangnan|chengdu|zixi|wulumuqixian|diebu|miluo|shilou|xiamen|tailai|wugang|heyang|yumin|wuji|zhalantun|longhai'.
	    '|yangquan|hefeng|wuhe|jincheng|shiyan|yuxi|xiayi|lishi|yanzhou|longnan|suichang|mianxian|shaodong|chenzhou|fengjie|yingtan|wulong|buerjin|bishan'.
	    '|suniteyouqi|yongxiu|yaan|chengduo|yongji|liulin|longgeer|panan|kezi|tianlin|beijing|zhanjiang|yiyang|jishishan|xinyuan|shihezi|lijin|lancang|'.
	    'xianju|laiyang|yuyao|haiyuan|chunan|balinzuoqi|fenghuang|jiaoling|pingyang|dongying|puer|xinghai|wuping|jize|qingchuan|shaoguan|fuhai|jiujiang|'.
	    'tengxian|jixi|henan|wujin|dafang|jintan|dongshan|nangqian|yecheng|yichuan|zigui|fenyi|zhoushan|baise|fengning|hezheng|xinghua|leiyang|gaize|badong'.
	    '|yuanyang|lijiang|hainanzhou|pubei|pingle|lushui|chongren|yinjiang|dongfang|jiyuan|shenzhou|junlian|laoting|doumen|baoji|tongbai|xinhuang|baoshan'.
	    '|ludian|xinhe|xianfeng|lulong|alukeerqinqi|xinji|wugong|xining|qingyang|jinxiu|wensu|shangcheng|dingyuan|kedong|dujiangyan|zhengxiangbaiqi|'.
	    'chabuchaer|yongsheng|pingluo|jinping|pingguo|wuqing|xingan|mishan|bozhou|yueyangxian|tanchang|qufu|xiangfen|yongzhou|shufu|liuzhou|guangzong|'.
	    'guyuanxian|taicang|huaibei|foshan|xiangfan|maigaiti|ruichang|rongcheng|puding|weili|baoying|jinxian|xunxian|xiping|conghua|qinhuangdao|huangping|'.
	    'quwo|yanan|ziyun|seda|xinjiang|danfeng|dingxi|huailai|zezhou|jingyuan|wuzhai|gaocheng|jishan|xiushan|hanyin|huadian|jimo|dazhu|keerqinzuoyihouqi|'.
	    'qiubei|jiange|jinhuaxian|jiaocheng|yumen|benxi|qionglai|huaying|jingan|changzhou|helong|chongyi|shangshui|shuangbai|dongan|shahe|huichang|jiayuguan'.
	    '|fengxian|fuxin|daocheng|mengla|xinxian|jinyang|yongtai|tianzhen|neixiang|shawan|miquan|nanxiong|dangyang|chibi|laiwu|lanxi|boye|ruijin|jianping|'.
	    'daning|hancheng|gaoyou|longjiang|ninghai|xunyang|fenggang|luhe|zhouzhi|xixia|gaotang|duan|shengzhou|tongchuan|shouyang|ningxiang|shulan|fengnan|'.
	    'hangjinqi|hengfeng|changtai|tongjiang|zhiduo|guiyang|jinhu|raoyang|chunhua|kaiyang|liucheng|weixi|jinxi|changli|cangzhou|mangkang|ningbo|guangde'.
	    '|qinxian|shandong|miyi|qinglong|lianyuan|weichang|shuangliao|xizang|changshaxian|longmen|liaoyuan|shengda|jingyu|deqin|zhaoan|shuifu|etuokeqi|'.
	    'mengyin|pishan|xiangzhou|batang|xinye|yanchi|shengsi|xuanzhou|yuanmou|zengcheng|naqu|jinxiang|yongren|guiding|dingqing|yikezhao|fuping|mizhi|'.
	    'longjing|changji|bailang|xingshan|luancheng|dongtai|baoting|chengde|shunchang|dalian|keerqinyouyiqianqi|zhangzi|taole|lujiang|weiyuan|shangzhou|'.
	    'xingwen|xinyouqi|zhongning|mengzhou|shibing|luxi|wuhu|mudanjiang|pulandian|deqing|shixing|shanwei|xingyang|mianyang|boluo|wudu|tiandeng|xuanhan|'.
	    'wenzhou|anji|acheng|wannian|zhanhua|yunnan|dongxiang|milin|anlu|suibin|longxi|chenghai|kulunqi|daoxian|loufan|cixi|funan|qinan|luobei|dianbai|wuqiao|'.
	    'minxian|taian|fuchuan|renbu|wuqiang|cangnan|yangxin|chahaeryouyihouqi|linxia|meitan|xilinhaote|tumen|dehua|dushan|guanyun|hanshou|lishu|manasi|'.
	    'kangma|zhenyuan|binxian|chaling|wulatehouqi|longli|lingyuan|nimu|lingbao|lantian|yanshi|pingjiang|qingzhou|qidong|baicheng|naquxian|liannan|'.
	    'zhucheng|jixian|kuche|zhongmou|wuyi|yanyuan|xinzheng|lushi|jieshou|luchuan|sanya|qimen|shimen|qumalai|jiangchuan|mianzhu|dongliao|kuancheng|'.
	    'kunming|aletai|tianquan|jinghong|jingyang|feidong|jin|xishan|nanjing|ningwu|yonghe|beiliu|tongshan|boli|fuzhou|ruzhou|taikang|jingle|gutian|'.
	    'wanning|zhongshaqundao|hulunbeiermeng|longzhou|zhongfang|puan|tongde|sanmenxia|hongya|changshan|xindu|mengshan|qingtian|lucheng|wuzhou|longquan'.
	    '|huanan|jiangning|guannan|chengdexian|menghai|chishui|pengze|laiyuan|rizhao|guangnan|hepu|tianchang|anshun|anxi|wuming|ruyang|xiaoyi|rongxian|'.
	    'rangtang|mashan|tieling|huangling|yongxing|fogang|guanghe';
?>